### ISSUE TITLE
Problemi di sicurezza su Windows

### ISSUE THREAD

**Issue by ALF3run** [Be4t5/Letfreex#26]
Attualmente il vostro servizio web, come la vostra guida afferma, può essere usufruito permettendo le richieste Cross Origin nel browser. Tuttavia in browser come Google Chrome, che si basano sul progetto Chromium, ciò equivale a disabilitare le same-origin policy attraverso il flag --disable-web-security ([http://peter.sh/experiments/chromium-command-line-switches/#disable-web-security](http://peter.sh/experiments/chromium-command-line-switches/#disable-web-security)) lasciando l'utente maggiormente esposto a svariati rischi informatici durante la loro normale navigazione web ([https://code.google.com/archive/p/browsersec/wikis/Part2.wiki#Same-origin_policy](https://code.google.com/archive/p/browsersec/wikis/Part2.wiki#Same-origin_policy)).
Inoltre, lo stesso eseguibile che fornite alla pagina [http://letfreex.com/letfreex-web/](http://letfreex.com/letfreex-web/), viene marcato da Google Chrome come rischioso, e il suo download viene interrotto, suppongo perché va a modificare proprio queste impostazioni del browser.

Confido, che siate consapevoli del problema e stiate già lavorando per risolverlo, tuttavia ritengo opportuno che gli utenti siano informati dei rischi che corrono.

Io personalmente sto usando un collegamento a chrome con una destinazione modificata in modo da avere una sessione non sicura solo quando uso Letfreex. Riporto qui i passaggi nel caso interessino a qualcuno:

1. Creare un nuovo collegamento a Google Chrome sul desktop e rinominatelo "Letfreex Web"
2. Click su di esso con il tasto destro del mouse
3. Selezionate "Proprietà"
4. Nella finestra che si apre, assicuratevi di trovarvi nella scheda "Collegamento" (in alto)
5. Nel campo "Destinazione" aggiungete, senza cancellare il contenuto presente, la seguente riga `-kiosk --disable-web-security --user-data-dir="C:\Users\%USERNAME%\AppData\Local\Google\Chrome\User Data\DWS" --disable-infobars`, precedendola con uno spazio.
L'intero campo dovrebbe essere simile a questo: 
```
"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" -kiosk --disable-web-security --user-data-dir="C:\Users\%USERNAME%\AppData\Local\Google\Chrome\User Data\DWS" --disable-infobars
```

Il codice aggiuntivo ha l'effetto di permettere il CrossOrigin (--disable-web-security), disabilitare gli avvisi di Chrome che ricordano che lo state usando in modalità non sicura (--disable-infobars), creare una nuova sessione web diversa da quella usata abitualmente (--user-data-dir="C:\Users\%USERNAME%\AppData\Local\Google\Chrome\User Data\DWS"), avviare il browser in modalità fullscreen e senza interfaccia (-kiosk).

**Comment by Be4t5** [comment]
In effetti il nostro eseguibile non fa altro che lasciare da linea di comando chrome con tutte le opzioni che hai elencato sopra (tranne -kiosk e --disable-infobars, grazie, le aggiungeremo). Abbiamo creato l'eseguibile proprio per permettere all'utente di usare Letfreex web con una differente sessione. Sul sito non spieghiamo come abilitare il cross origin appositamente: se un utente lo abilita in altre maniere, è consapevole di cosa sta facendo.

Il fatto che gli antivirus riconoscano come malevolo il nostro eseguibile è per il semplice fatto che si tratta di uno script bat convertito in exe, che equivale ad affibbiargli un cartellone con scritto sopra "SONO UN VIRUS" :)  
Se per caso, visto che sembri preparato su questo argomento, conoscessi un metodo per rendere "trusted" il nostro script convertito in eseguibile, non esitare a segnalarcelo, noi purtroppo non abbiamo tempo di approfondire

**Comment by ALF3run** [comment]
Capisco le vostre ragioni, tuttavia trattandosi di un progetto open source penso sarebbe meglio per il suo stesso sviluppo se gli utenti fossero adeguatamente informati a proposito. Inoltre potreste evitare problemi di responsabilità in caso di uso scorretto del servizio.

Per quanto riguarda lo script bat, non so come potreste renderlo "trusted". Penso che la cosa migliore sarebbe trovare un modo per aggirare il problema CrossOrigin settando correttamente gli headers durante la richiesta ajax, anche se non so se sia così semplice dato che non avete controllo sui server.
L'alternativa è non usare script bat e scrivere un vero eseguibile. Premetto che è un po' che non programmo in C ma ho comunque voluto fare un tentativo con questo codice:
```
#include <stdio.h>
#include <stdlib.h>

int main()
{
    system("\"\"%PROGRAMFILES%/Google/Chrome/Application/chrome.exe\" http://web.letfreex.com --disable-web-security -kiosk --disable-infobars --user-data-dir=\"%USERPROFILE%/AppData/Local/Google/Chrome/User Data/DWS\"");
    return 0;
}
```
Ho creato un [eseguibile](https://drive.google.com/open?id=0Bx7zcUJBNY6-elIwNjgzM3Qza2M), aggiunto la vostra icona utilizzando [Resource Hacker](http://www.angusj.com/resourcehacker/) e l'ho testato su [virustotal.com](https://www.virustotal.com). La prima immagine raffigura i risultati del batch convertito la seconda quelli dell'eseguibile scritto in C:
![virustotal_letfreex_bat](https://user-images.githubusercontent.com/2693877/27262490-228c63c6-5458-11e7-83fb-f2c56eac4f17.png)
![virustotal_letfreex_c](https://user-images.githubusercontent.com/2693877/27262496-2648e890-5458-11e7-80b1-f35b3c92920d.png)

**Comment by Be4t5** [comment]
Grazie per il tuo lavoro. Dopo aver provato il tuo eseguibile ho riscontrato due problemi: il primo è che la console rimane aperta (ma questo non è che sia un gran problema), il secondo è che non c'è modo di uscire dalla modalità kiosk se non utilizzando Alt + f4. Il che potrebbe essere un problema dato che non tutti lo sanno. Se riesci a ricompilare l'eseguibile senza modalità kiosk lo sostituiamo a quello attualmente pubblicato, visto che agli antivirus piace di più :)

**Comment by ALF3run** [comment]
Ho scritto del nuovo codice per risolvere entrambi i problemi:
```
#include <stdio.h>
#include <stdlib.h>
#include <windows.h>
#include <ShellApi.h>
#include <shlobj.h>

#define MAX_LENGTH 1024

int main()
{
    char APP_DATA_LOCAL[MAX_PATH] = "";
    char param[MAX_LENGTH] = "-app=http://www.web.letfreex.com --disable-web-security --disable-infobars --user-data-dir=";

    SHGetFolderPathA(NULL, CSIDL_LOCAL_APPDATA, NULL, 0, APP_DATA_LOCAL);
    strcat(param, APP_DATA_LOCAL);
    strcat(param, "\\Letfreex\\");

    ShellExecuteA(NULL,NULL,"chrome.exe",param,"%PROGRAMFILES%\\google\\chrome\\application\\",SW_SHOWMAXIMIZED);
    return 0;
}
```
Nuovo eseguibile [qui](https://drive.google.com/open?id=0Bx7zcUJBNY6-NFVucGgycTNZR2c). Grazie a voi.

**Comment by Be4t5** [comment]
Ottimo lavoro, così è quasi perfetto! Se riuscissi a mettere il logo anche sulla barra in alto e nella barra della applicazioni di Windows quando è aperta, sarebbe perfetta. Grazie, ci stai togliendo una grossa grana!

**Comment by ALF3run** [comment]
Penso che anche l'icona in basso sia la favicon perché è gestita da chrome e non credo di poterla cambiare dall'eseguibile. In ogni caso aspettate a ringraziarmi perché mi sono accorto che usando la modalità -app di chrome non fa aprire i link dei video.

**Comment by Be4t5** [comment]
Non avevo notato, ma quello non è essenziale... Se si riesce a far funzionare, meglio altrimenti mettiamo un "mostra link" permettendo di copiare il link al video direttamente, che tanto sarebbe utile in ogni caso

**Comment by ALF3run** [comment]
Il problema è legato al blocco popup di chrome. Se lo si disabilità i link vengono aperti in una nuova istanza  non sicura del browser ma a quel punto l'application mode in cui viene lanciato il programma con l'eseguibile perde di senso. Se poteste aprire il link in un iframe nella stessa pagina penso otterreste la miglior soluzione, permettendo la visione, aumentando la sicurezza e mantenendo l'aspetto di un programma invece che di una pagina web.
